package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArrangementId generated by hbm2java
 */
@Embeddable
public class ArrangementId implements java.io.Serializable {

	/**
	 * 
	 */
	private BigDecimal idHotel;
	private BigDecimal idArrangement;

	public ArrangementId() {
	}

	public ArrangementId(BigDecimal idHotel, BigDecimal idArrangement) {
		this.idHotel = idHotel;
		this.idArrangement = idArrangement;
	}

	@Column(name = "ID_HOTEL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdHotel() {
		return this.idHotel;
	}

	public void setIdHotel(BigDecimal idHotel) {
		this.idHotel = idHotel;
	}

	@Column(name = "ID_ARRANGEMENT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdArrangement() {
		return this.idArrangement;
	}

	public void setIdArrangement(BigDecimal idArrangement) {
		this.idArrangement = idArrangement;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArrangementId))
			return false;
		ArrangementId castOther = (ArrangementId) other;

		return ((this.getIdHotel() == castOther.getIdHotel()) || (this.getIdHotel() != null
				&& castOther.getIdHotel() != null && this.getIdHotel().equals(castOther.getIdHotel())))
				&& ((this.getIdArrangement() == castOther.getIdArrangement())
						|| (this.getIdArrangement() != null && castOther.getIdArrangement() != null
								&& this.getIdArrangement().equals(castOther.getIdArrangement())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdHotel() == null ? 0 : this.getIdHotel().hashCode());
		result = 37 * result + (getIdArrangement() == null ? 0 : this.getIdArrangement().hashCode());
		return result;
	}

}
