package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Arrangement generated by hbm2java
 */
@Entity
@Table(name = "ARRANGEMENT")
public class Arrangement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ArrangementId id;
	private Hotel hotel;
	private String abrvArrangement;
	private String LArrangement;
	private Set<MvmentPrix> mvmentPrixes = new HashSet<MvmentPrix>(0);

	public Arrangement() {
	}

	public Arrangement(ArrangementId id, Hotel hotel) {
		this.id = id;
		this.hotel = hotel;
	}

	public Arrangement(ArrangementId id, Hotel hotel, String abrvArrangement, String LArrangement,
			Set<MvmentPrix> mvmentPrixes) {
		this.id = id;
		this.hotel = hotel;
		this.abrvArrangement = abrvArrangement;
		this.LArrangement = LArrangement;
		this.mvmentPrixes = mvmentPrixes;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idHotel", column = @Column(name = "ID_HOTEL", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idArrangement", column = @Column(name = "ID_ARRANGEMENT", nullable = false, precision = 22, scale = 0)) })
	public ArrangementId getId() {
		return this.id;
	}

	public void setId(ArrangementId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HOTEL", nullable = false, insertable = false, updatable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "ABRV_ARRANGEMENT", length = 30)
	public String getAbrvArrangement() {
		return this.abrvArrangement;
	}

	public void setAbrvArrangement(String abrvArrangement) {
		this.abrvArrangement = abrvArrangement;
	}

	@Column(name = "L_ARRANGEMENT", length = 256)
	public String getLArrangement() {
		return this.LArrangement;
	}

	public void setLArrangement(String LArrangement) {
		this.LArrangement = LArrangement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arrangement")
	public Set<MvmentPrix> getMvmentPrixes() {
		return this.mvmentPrixes;
	}

	public void setMvmentPrixes(Set<MvmentPrix> mvmentPrixes) {
		this.mvmentPrixes = mvmentPrixes;
	}

}
