package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Avion generated by hbm2java
 */
@Entity
@Table(name = "AVION")
public class Avion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idAvion;
	private String nomAvion;
	private String airline;
	private String abrvAvion;
	private String typeAvion;
	private Set<MvmentPrix> mvmentPrixes = new HashSet<MvmentPrix>(0);
	private Set<ClassVol> classVols = new HashSet<ClassVol>(0);

	public Avion() {
	}

	public Avion(BigDecimal idAvion) {
		this.idAvion = idAvion;
	}

	public Avion(BigDecimal idAvion, String nomAvion, String airline, String abrvAvion, String typeAvion,
			Set<MvmentPrix> mvmentPrixes, Set<ClassVol> classVols) {
		this.idAvion = idAvion;
		this.nomAvion = nomAvion;
		this.airline = airline;
		this.abrvAvion = abrvAvion;
		this.typeAvion = typeAvion;
		this.mvmentPrixes = mvmentPrixes;
		this.classVols = classVols;
	}

	@Id

	@Column(name = "ID_AVION", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdAvion() {
		return this.idAvion;
	}

	public void setIdAvion(BigDecimal idAvion) {
		this.idAvion = idAvion;
	}

	@Column(name = "NOM_AVION", length = 30)
	public String getNomAvion() {
		return this.nomAvion;
	}

	public void setNomAvion(String nomAvion) {
		this.nomAvion = nomAvion;
	}

	@Column(name = "AIRLINE", length = 50)
	public String getAirline() {
		return this.airline;
	}

	public void setAirline(String airline) {
		this.airline = airline;
	}

	@Column(name = "ABRV_AVION", precision = 22, scale = 0)
	public String getAbrvAvion() {
		return this.abrvAvion;
	}

	public void setAbrvAvion(String abrvAvion) {
		this.abrvAvion = abrvAvion;
	}

	@Column(name = "TYPE_AVION", length = 50)
	public String getTypeAvion() {
		return this.typeAvion;
	}

	public void setTypeAvion(String typeAvion) {
		this.typeAvion = typeAvion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "avion")
	public Set<MvmentPrix> getMvmentPrixes() {
		return this.mvmentPrixes;
	}

	public void setMvmentPrixes(Set<MvmentPrix> mvmentPrixes) {
		this.mvmentPrixes = mvmentPrixes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "avion")
	public Set<ClassVol> getClassVols() {
		return this.classVols;
	}

	public void setClassVols(Set<ClassVol> classVols) {
		this.classVols = classVols;
	}

}
