package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClassVolId generated by hbm2java
 */
@Embeddable
public class ClassVolId implements java.io.Serializable {

	private BigDecimal idAvion;
	private BigDecimal idClassVol;

	public ClassVolId() {
	}

	public ClassVolId(BigDecimal idAvion, BigDecimal idClassVol) {
		this.idAvion = idAvion;
		this.idClassVol = idClassVol;
	}

	@Column(name = "ID_AVION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdAvion() {
		return this.idAvion;
	}

	public void setIdAvion(BigDecimal idAvion) {
		this.idAvion = idAvion;
	}

	@Column(name = "ID_CLASS_VOL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdClassVol() {
		return this.idClassVol;
	}

	public void setIdClassVol(BigDecimal idClassVol) {
		this.idClassVol = idClassVol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClassVolId))
			return false;
		ClassVolId castOther = (ClassVolId) other;

		return ((this.getIdAvion() == castOther.getIdAvion()) || (this.getIdAvion() != null
				&& castOther.getIdAvion() != null && this.getIdAvion().equals(castOther.getIdAvion())))
				&& ((this.getIdClassVol() == castOther.getIdClassVol())
						|| (this.getIdClassVol() != null && castOther.getIdClassVol() != null
								&& this.getIdClassVol().equals(castOther.getIdClassVol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdAvion() == null ? 0 : this.getIdAvion().hashCode());
		result = 37 * result + (getIdClassVol() == null ? 0 : this.getIdClassVol().hashCode());
		return result;
	}

}
