package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassVol generated by hbm2java
 */
@Entity
@Table(name = "CLASS_VOL")
public class ClassVol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ClassVolId id;
	private Avion avion;
	private String abrvClass;
	private String LClass;
	private Set<MvmentPrix> mvmentPrixes = new HashSet<MvmentPrix>(0);

	public ClassVol() {
	}

	public ClassVol(ClassVolId id, Avion avion) {
		this.id = id;
		this.avion = avion;
	}

	public ClassVol(ClassVolId id, Avion avion, String abrvClass, String LClass, Set<MvmentPrix> mvmentPrixes) {
		this.id = id;
		this.avion = avion;
		this.abrvClass = abrvClass;
		this.LClass = LClass;
		this.mvmentPrixes = mvmentPrixes;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAvion", column = @Column(name = "ID_AVION", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idClassVol", column = @Column(name = "ID_CLASS_VOL", nullable = false, precision = 22, scale = 0)) })
	public ClassVolId getId() {
		return this.id;
	}

	public void setId(ClassVolId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AVION", nullable = false, insertable = false, updatable = false)
	public Avion getAvion() {
		return this.avion;
	}

	public void setAvion(Avion avion) {
		this.avion = avion;
	}

	@Column(name = "ABRV_CLASS", length = 20)
	public String getAbrvClass() {
		return this.abrvClass;
	}

	public void setAbrvClass(String abrvClass) {
		this.abrvClass = abrvClass;
	}

	@Column(name = "L_CLASS", length = 200)
	public String getLClass() {
		return this.LClass;
	}

	public void setLClass(String LClass) {
		this.LClass = LClass;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classVol")
	public Set<MvmentPrix> getMvmentPrixes() {
		return this.mvmentPrixes;
	}

	public void setMvmentPrixes(Set<MvmentPrix> mvmentPrixes) {
		this.mvmentPrixes = mvmentPrixes;
	}

}
