package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name = "HOTEL")
public class Hotel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idHotel;
	private String nomHotel;
	private String adreHotel;
	private String villeHotel;
	private String pays;
	private String abrvHotel;
	private String categorie;
	private Set<Periode> periodes = new HashSet<Periode>(0);
	private Set<Arrangement> arrangements = new HashSet<Arrangement>(0);
	private Set<Supplement> supplements = new HashSet<Supplement>(0);
	private Set<TypeChambre> typeChambres = new HashSet<TypeChambre>(0);

	public Hotel() {
	}

	public Hotel(BigDecimal idHotel) {
		this.idHotel = idHotel;
	}

	public Hotel(BigDecimal idHotel, String nomHotel, String adreHotel, String villeHotel, String pays,
			String abrvHotel,String categorie, Set<Periode> periodes, Set<Arrangement> arrangements, Set<Supplement> supplements,
			Set<TypeChambre> typeChambres) {
		this.idHotel = idHotel;
		this.nomHotel = nomHotel;
		this.adreHotel = adreHotel;
		this.villeHotel = villeHotel;
		this.pays = pays;
		this.abrvHotel = abrvHotel;
		this.categorie=categorie;
		this.periodes = periodes;
		this.arrangements = arrangements;
		this.supplements = supplements;
		this.typeChambres = typeChambres;
	}

	@Id

	@Column(name = "ID_HOTEL", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdHotel() {
		return this.idHotel;
	}

	public void setIdHotel(BigDecimal idHotel) {
		this.idHotel = idHotel;
	}

	@Column(name = "NOM_HOTEL", length = 25)
	public String getNomHotel() {
		return this.nomHotel;
	}

	public void setNomHotel(String nomHotel) {
		this.nomHotel = nomHotel;
	}

	@Column(name = "ADRE_HOTEL", length = 25)
	public String getAdreHotel() {
		return this.adreHotel;
	}

	public void setAdreHotel(String adreHotel) {
		this.adreHotel = adreHotel;
	}

	@Column(name = "VILLE_HOTEL", length = 25)
	public String getVilleHotel() {
		return this.villeHotel;
	}

	public void setVilleHotel(String villeHotel) {
		this.villeHotel = villeHotel;
	}

	@Column(name = "PAYS", length = 20)
	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	@Column(name = "ABRV_HOTEL", length = 20)
	public String getAbrvHotel() {
		return this.abrvHotel;
	}

	public void setAbrvHotel(String abrvHotel) {
		this.abrvHotel = abrvHotel;
	}
	
	@Column(name = "CATEGORIE", length = 20)
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String abrvHotel) {
		this.abrvHotel = abrvHotel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<Periode> getPeriodes() {
		return this.periodes;
	}

	public void setPeriodes(Set<Periode> periodes) {
		this.periodes = periodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<Arrangement> getArrangements() {
		return this.arrangements;
	}

	public void setArrangements(Set<Arrangement> arrangements) {
		this.arrangements = arrangements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<Supplement> getSupplements() {
		return this.supplements;
	}

	public void setSupplements(Set<Supplement> supplements) {
		this.supplements = supplements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<TypeChambre> getTypeChambres() {
		return this.typeChambres;
	}

	public void setTypeChambres(Set<TypeChambre> typeChambres) {
		this.typeChambres = typeChambres;
	}

}
