package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PeriodeSupplement generated by hbm2java
 */
@Entity
@Table(name = "PERIODE_SUPPLEMENT")
public class PeriodeSupplement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PeriodeSupplementId id;
	private Jour jour;
	private Periode periode;
	private Supplement supplement;
	private BigDecimal prixSupp;
	private Character actif;

	public PeriodeSupplement() {
	}

	public PeriodeSupplement(PeriodeSupplementId id, Jour jour, Periode periode, Supplement supplement) {
		this.id = id;
		this.jour = jour;
		this.periode = periode;
		this.supplement = supplement;
	}

	public PeriodeSupplement(PeriodeSupplementId id, Jour jour, Periode periode, Supplement supplement,
			BigDecimal prixSupp, Character actif) {
		this.id = id;
		this.jour = jour;
		this.periode = periode;
		this.supplement = supplement;
		this.prixSupp = prixSupp;
		this.actif = actif;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idHotel", column = @Column(name = "ID_HOTEL", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idSupp", column = @Column(name = "ID_SUPP", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idPeriode", column = @Column(name = "ID_PERIODE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idJour", column = @Column(name = "ID_JOUR", nullable = false, precision = 22, scale = 0)) })
	public PeriodeSupplementId getId() {
		return this.id;
	}

	public void setId(PeriodeSupplementId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JOUR",  insertable = false, updatable = false)
	public Jour getJour() {
		return this.jour;
	}

	public void setJour(Jour jour) {
		this.jour = jour;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_HOTEL", referencedColumnName = "ID_HOTEL", insertable = false, updatable = false),
			@JoinColumn(name = "ID_PERIODE", referencedColumnName = "ID_PERIODE",  insertable = false, updatable = false) })
	public Periode getPeriode() {
		return this.periode;
	}

	public void setPeriode(Periode periode) {
		this.periode = periode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_HOTEL", referencedColumnName = "ID_HOTEL",  insertable = false, updatable = false),
			@JoinColumn(name = "ID_SUPP", referencedColumnName = "ID_SUPP",  insertable = false, updatable = false) })
	public Supplement getSupplement() {
		return this.supplement;
	}

	public void setSupplement(Supplement supplement) {
		this.supplement = supplement;
	}

	@Column(name = "PRIX_SUPP", precision = 22, scale = 0)
	public BigDecimal getPrixSupp() {
		return this.prixSupp;
	}

	public void setPrixSupp(BigDecimal prixSupp) {
		this.prixSupp = prixSupp;
	}

	@Column(name = "ACTIF", length = 1)
	public Character getActif() {
		return this.actif;
	}

	public void setActif(Character actif) {
		this.actif = actif;
	}

}
