package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Periode generated by hbm2java
 */
@Entity
@Table(name = "PERIODE")
public class Periode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PeriodeId id;
	private Hotel hotel;
	private String abrvPeriode;
	private String LPeriode;
	private Date dtDebut;
	private Date dtFin;
	private Character closed;
	private Set<MvmentPrix> mvmentPrixes = new HashSet<MvmentPrix>(0);
	private Set<PeriodeSupplement> periodeSupplements = new HashSet<PeriodeSupplement>(0);
	private Set<Reduction> reductions = new HashSet<Reduction>(0);

	public Periode() {
	}

	public Periode(PeriodeId id, Hotel hotel, String abrvPeriode) {
		this.id = id;
		this.hotel = hotel;
		this.abrvPeriode = abrvPeriode;
	}

	public Periode(PeriodeId id, Hotel hotel, String abrvPeriode, String LPeriode, Date dtDebut, Date dtFin,
			Character closed, Set<MvmentPrix> mvmentPrixes, Set<PeriodeSupplement> periodeSupplements,
			Set<Reduction> reductions) {
		this.id = id;
		this.hotel = hotel;
		this.abrvPeriode = abrvPeriode;
		this.LPeriode = LPeriode;
		this.dtDebut = dtDebut;
		this.dtFin = dtFin;
		this.closed = closed;
		this.mvmentPrixes = mvmentPrixes;
		this.periodeSupplements = periodeSupplements;
		this.reductions = reductions;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idHotel", column = @Column(name = "ID_HOTEL", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idPeriode", column = @Column(name = "ID_PERIODE", nullable = false, precision = 22, scale = 0)) })
	public PeriodeId getId() {
		return this.id;
	}

	public void setId(PeriodeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HOTEL", nullable = false, insertable = false, updatable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "ABRV_PERIODE", nullable = false, length = 20)
	public String getAbrvPeriode() {
		return this.abrvPeriode;
	}

	public void setAbrvPeriode(String abrvPeriode) {
		this.abrvPeriode = abrvPeriode;
	}

	@Column(name = "L_PERIODE", length = 200)
	public String getLPeriode() {
		return this.LPeriode;
	}

	public void setLPeriode(String LPeriode) {
		this.LPeriode = LPeriode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_DEBUT", length = 7)
	public Date getDtDebut() {
		return this.dtDebut;
	}

	public void setDtDebut(Date dtDebut) {
		this.dtDebut = dtDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_FIN", length = 7)
	public Date getDtFin() {
		return this.dtFin;
	}

	public void setDtFin(Date dtFin) {
		this.dtFin = dtFin;
	}

	@Column(name = "CLOSED", length = 1)
	public Character getClosed() {
		return this.closed;
	}

	public void setClosed(Character closed) {
		this.closed = closed;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periode")
	public Set<MvmentPrix> getMvmentPrixes() {
		return this.mvmentPrixes;
	}

	public void setMvmentPrixes(Set<MvmentPrix> mvmentPrixes) {
		this.mvmentPrixes = mvmentPrixes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periode")
	public Set<PeriodeSupplement> getPeriodeSupplements() {
		return this.periodeSupplements;
	}

	public void setPeriodeSupplements(Set<PeriodeSupplement> periodeSupplements) {
		this.periodeSupplements = periodeSupplements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periode")
	public Set<Reduction> getReductions() {
		return this.reductions;
	}

	public void setReductions(Set<Reduction> reductions) {
		this.reductions = reductions;
	}

}
