package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PeriodeId generated by hbm2java
 */
@Embeddable
public class PeriodeId implements java.io.Serializable {

	private BigDecimal idHotel;
	private BigDecimal idPeriode;

	public PeriodeId() {
	}

	public PeriodeId(BigDecimal idHotel, BigDecimal idPeriode) {
		this.idHotel = idHotel;
		this.idPeriode = idPeriode;
	}

	@Column(name = "ID_HOTEL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdHotel() {
		return this.idHotel;
	}

	public void setIdHotel(BigDecimal idHotel) {
		this.idHotel = idHotel;
	}

	@Column(name = "ID_PERIODE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPeriode() {
		return this.idPeriode;
	}

	public void setIdPeriode(BigDecimal idPeriode) {
		this.idPeriode = idPeriode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PeriodeId))
			return false;
		PeriodeId castOther = (PeriodeId) other;

		return ((this.getIdHotel() == castOther.getIdHotel()) || (this.getIdHotel() != null
				&& castOther.getIdHotel() != null && this.getIdHotel().equals(castOther.getIdHotel())))
				&& ((this.getIdPeriode() == castOther.getIdPeriode()) || (this.getIdPeriode() != null
						&& castOther.getIdPeriode() != null && this.getIdPeriode().equals(castOther.getIdPeriode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdHotel() == null ? 0 : this.getIdHotel().hashCode());
		result = 37 * result + (getIdPeriode() == null ? 0 : this.getIdPeriode().hashCode());
		return result;
	}

}
