package com.worldsoft.domain;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrmDestination generated by hbm2java
 */
@Entity
@Table(name = "PRM_DESTINATION")
public class PrmDestination implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idDest;
	private Avion avion;
	private String airDep;
	private String airArr;

	public PrmDestination() {
	}

	public PrmDestination(BigDecimal idDest, Avion avion, String airDep, String airArr) {
		this.idDest = idDest;
		this.avion = avion;
		this.airDep = airDep;
		this.airArr = airArr;
	}

	@Id

	@Column(name = "ID_DEST", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDest() {
		return this.idDest;
	}

	public void setIdDest(BigDecimal idDest) {
		this.idDest = idDest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AVION", nullable = false)
	public Avion getAvion() {
		return this.avion;
	}

	public void setAvion(Avion avion) {
		this.avion = avion;
	}

	@Column(name = "AIR_DEP", nullable = false, length = 10)
	public String getAirDep() {
		return this.airDep;
	}

	public void setAirDep(String airDep) {
		this.airDep = airDep;
	}

	@Column(name = "AIR_ARR", nullable = false, length = 10)
	public String getAirArr() {
		return this.airArr;
	}

	public void setAirArr(String airArr) {
		this.airArr = airArr;
	}

}
