package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "PROMOTION")
public class Promotion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idPromo;
	private Jour jour;
	private TypeChambre typeChambre;
	private String abrvPromotion;
	private String LProm;
	private Character flagServ;

	public Promotion() {
	}

	public Promotion(BigDecimal idPromo, TypeChambre typeChambre, String abrvPromotion) {
		this.idPromo = idPromo;
		this.typeChambre = typeChambre;
		this.abrvPromotion = abrvPromotion;
	}

	public Promotion(BigDecimal idPromo, Jour jour, TypeChambre typeChambre, String abrvPromotion, String LProm,
			Character flagServ) {
		this.idPromo = idPromo;
		this.jour = jour;
		this.typeChambre = typeChambre;
		this.abrvPromotion = abrvPromotion;
		this.LProm = LProm;
		this.flagServ = flagServ;
	}

	@Id

	@Column(name = "ID_PROMO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPromo() {
		return this.idPromo;
	}

	public void setIdPromo(BigDecimal idPromo) {
		this.idPromo = idPromo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JOUR")
	public Jour getJour() {
		return this.jour;
	}

	public void setJour(Jour jour) {
		this.jour = jour;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "ID_HOTEL", referencedColumnName = "ID_HOTEL", nullable = false),
			@JoinColumn(name = "ID_CHM", referencedColumnName = "ID_CHM", nullable = false) })
	public TypeChambre getTypeChambre() {
		return this.typeChambre;
	}

	public void setTypeChambre(TypeChambre typeChambre) {
		this.typeChambre = typeChambre;
	}

	@Column(name = "ABRV_PROMOTION", nullable = false, length = 20)
	public String getAbrvPromotion() {
		return this.abrvPromotion;
	}

	public void setAbrvPromotion(String abrvPromotion) {
		this.abrvPromotion = abrvPromotion;
	}

	@Column(name = "L_PROM", length = 250)
	public String getLProm() {
		return this.LProm;
	}

	public void setLProm(String LProm) {
		this.LProm = LProm;
	}

	@Column(name = "FLAG_SERV", length = 1)
	public Character getFlagServ() {
		return this.flagServ;
	}

	public void setFlagServ(Character flagServ) {
		this.flagServ = flagServ;
	}

}
