package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReductionId generated by hbm2java
 */
@Embeddable
public class ReductionId implements java.io.Serializable {

	private BigDecimal idHotel;
	private BigDecimal idPeriode;
	private BigDecimal idReduction;

	public ReductionId() {
	}

	public ReductionId(BigDecimal idHotel, BigDecimal idPeriode, BigDecimal idReduction) {
		this.idHotel = idHotel;
		this.idPeriode = idPeriode;
		this.idReduction = idReduction;
	}

	@Column(name = "ID_HOTEL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdHotel() {
		return this.idHotel;
	}

	public void setIdHotel(BigDecimal idHotel) {
		this.idHotel = idHotel;
	}

	@Column(name = "ID_PERIODE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPeriode() {
		return this.idPeriode;
	}

	public void setIdPeriode(BigDecimal idPeriode) {
		this.idPeriode = idPeriode;
	}

	@Column(name = "ID_REDUCTION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdReduction() {
		return this.idReduction;
	}

	public void setIdReduction(BigDecimal idReduction) {
		this.idReduction = idReduction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReductionId))
			return false;
		ReductionId castOther = (ReductionId) other;

		return ((this.getIdHotel() == castOther.getIdHotel()) || (this.getIdHotel() != null
				&& castOther.getIdHotel() != null && this.getIdHotel().equals(castOther.getIdHotel())))
				&& ((this.getIdPeriode() == castOther.getIdPeriode()) || (this.getIdPeriode() != null
						&& castOther.getIdPeriode() != null && this.getIdPeriode().equals(castOther.getIdPeriode())))
				&& ((this.getIdReduction() == castOther.getIdReduction())
						|| (this.getIdReduction() != null && castOther.getIdReduction() != null
								&& this.getIdReduction().equals(castOther.getIdReduction())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdHotel() == null ? 0 : this.getIdHotel().hashCode());
		result = 37 * result + (getIdPeriode() == null ? 0 : this.getIdPeriode().hashCode());
		result = 37 * result + (getIdReduction() == null ? 0 : this.getIdReduction().hashCode());
		return result;
	}

}
