package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reduction generated by hbm2java
 */
@Entity
@Table(name = "REDUCTION")
public class Reduction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ReductionId id;
	private Periode periode;
	private char actifReduction;
	private String LReduction;
	private String abrvReduction;
	private Character flagServ;

	public Reduction() {
	}

	public Reduction(ReductionId id, Periode periode, char actifReduction, String abrvReduction) {
		this.id = id;
		this.periode = periode;
		this.actifReduction = actifReduction;
		this.abrvReduction = abrvReduction;
	}

	public Reduction(ReductionId id, Periode periode, char actifReduction, String LReduction, String abrvReduction,
			Character flagServ) {
		this.id = id;
		this.periode = periode;
		this.actifReduction = actifReduction;
		this.LReduction = LReduction;
		this.abrvReduction = abrvReduction;
		this.flagServ = flagServ;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idHotel", column = @Column(name = "ID_HOTEL", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idPeriode", column = @Column(name = "ID_PERIODE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idReduction", column = @Column(name = "ID_REDUCTION", nullable = false, precision = 22, scale = 0)) })
	public ReductionId getId() {
		return this.id;
	}

	public void setId(ReductionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_HOTEL", referencedColumnName = "ID_HOTEL",  insertable = false, updatable = false),
			@JoinColumn(name = "ID_PERIODE", referencedColumnName = "ID_PERIODE",  insertable = false, updatable = false) })
	public Periode getPeriode() {
		return this.periode;
	}

	public void setPeriode(Periode periode) {
		this.periode = periode;
	}

	@Column(name = "ACTIF_REDUCTION", nullable = false, length = 1)
	public char getActifReduction() {
		return this.actifReduction;
	}

	public void setActifReduction(char actifReduction) {
		this.actifReduction = actifReduction;
	}

	@Column(name = "L_REDUCTION", length = 200)
	public String getLReduction() {
		return this.LReduction;
	}

	public void setLReduction(String LReduction) {
		this.LReduction = LReduction;
	}

	@Column(name = "ABRV_REDUCTION", nullable = false, length = 20)
	public String getAbrvReduction() {
		return this.abrvReduction;
	}

	public void setAbrvReduction(String abrvReduction) {
		this.abrvReduction = abrvReduction;
	}

	@Column(name = "FLAG_SERV", length = 1)
	public Character getFlagServ() {
		return this.flagServ;
	}

	public void setFlagServ(Character flagServ) {
		this.flagServ = flagServ;
	}

}
