package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefFonction generated by hbm2java
 */
@Entity
@Table(name = "REF_FONCTION")
public class RefFonction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idFonction;
	private String LFonction;
	private Set<RoleFonction> roleFonctions = new HashSet<RoleFonction>(0);

	public RefFonction() {
	}

	public RefFonction(BigDecimal idFonction) {
		this.idFonction = idFonction;
	}

	public RefFonction(BigDecimal idFonction, String LFonction, Set<RoleFonction> roleFonctions) {
		this.idFonction = idFonction;
		this.LFonction = LFonction;
		this.roleFonctions = roleFonctions;
	}

	@Id

	@Column(name = "ID_FONCTION", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdFonction() {
		return this.idFonction;
	}

	public void setIdFonction(BigDecimal idFonction) {
		this.idFonction = idFonction;
	}

	@Column(name = "L_FONCTION", length = 100)
	public String getLFonction() {
		return this.LFonction;
	}

	public void setLFonction(String LFonction) {
		this.LFonction = LFonction;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refFonction")
	public Set<RoleFonction> getRoleFonctions() {
		return this.roleFonctions;
	}

	public void setRoleFonctions(Set<RoleFonction> roleFonctions) {
		this.roleFonctions = roleFonctions;
	}

}
