package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefUtilisateur generated by hbm2java
 */
@Entity
@Table(name = "REF_UTILISATEUR")
public class RefUtilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idUtilisateur;
	private RefTiers refTiers;
	private String nomRefUtilisateur;
	private String logUtilisateur;
	private String passwUtilisateur;

	public RefUtilisateur() {
	}

	public RefUtilisateur(BigDecimal idUtilisateur, RefTiers refTiers, String logUtilisateur, String passwUtilisateur) {
		this.idUtilisateur = idUtilisateur;
		this.refTiers = refTiers;
		this.logUtilisateur = logUtilisateur;
		this.passwUtilisateur = passwUtilisateur;
	}

	public RefUtilisateur(BigDecimal idUtilisateur, RefTiers refTiers, String nomRefUtilisateur, String logUtilisateur,
			String passwUtilisateur) {
		this.idUtilisateur = idUtilisateur;
		this.refTiers = refTiers;
		this.nomRefUtilisateur = nomRefUtilisateur;
		this.logUtilisateur = logUtilisateur;
		this.passwUtilisateur = passwUtilisateur;
	}

	@Id

	@Column(name = "ID_UTILISATEUR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(BigDecimal idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REF_TIERS", nullable = false)
	public RefTiers getRefTiers() {
		return this.refTiers;
	}

	public void setRefTiers(RefTiers refTiers) {
		this.refTiers = refTiers;
	}

	@Column(name = "NOM_REF_UTILISATEUR", length = 30)
	public String getNomRefUtilisateur() {
		return this.nomRefUtilisateur;
	}

	public void setNomRefUtilisateur(String nomRefUtilisateur) {
		this.nomRefUtilisateur = nomRefUtilisateur;
	}

	@Column(name = "LOG_UTILISATEUR", nullable = false, length = 100)
	public String getLogUtilisateur() {
		return this.logUtilisateur;
	}

	public void setLogUtilisateur(String logUtilisateur) {
		this.logUtilisateur = logUtilisateur;
	}

	@Column(name = "PASSW_UTILISATEUR", nullable = false, length = 100)
	public String getPasswUtilisateur() {
		return this.passwUtilisateur;
	}

	public void setPasswUtilisateur(String passwUtilisateur) {
		this.passwUtilisateur = passwUtilisateur;
	}

}
