package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "RESERVATION")
public class Reservation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ReservationId id;
	private RefTiers refTiers;
	private BigDecimal prix;
	private Date dateReserv;
	private Date startDate;
	private Date endDate;
	private String airPortDepart;
	private String airPortArrive;
	private String hotel;
	private String LResr;

	private String villeHotel;
	private String pays;
	private String typeChambre;
	private String categorie;

	public Reservation() {
	}

	public Reservation(ReservationId id, RefTiers refTiers) {
		this.id = id;
		this.refTiers = refTiers;
	}

	public Reservation(ReservationId id, RefTiers refTiers, BigDecimal prix, Date dateReserv, String LResr) {
		this.id = id;
		this.refTiers = refTiers;
		this.prix = prix;
		this.dateReserv = dateReserv;
		this.LResr = LResr;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idRefTiers", column = @Column(name = "ID_REF_TIERS", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idReserv", column = @Column(name = "ID_RESERV", nullable = false, precision = 22, scale = 0)) })
	public ReservationId getId() {
		return this.id;
	}

	public void setId(ReservationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REF_TIERS", insertable = false, updatable = false)
	public RefTiers getRefTiers() {
		return this.refTiers;
	}

	public void setRefTiers(RefTiers refTiers) {
		this.refTiers = refTiers;
	}

	@Column(name = "PRIX", precision = 22, scale = 0)
	public BigDecimal getPrix() {
		return this.prix;
	}

	public void setPrix(BigDecimal prix) {
		this.prix = prix;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_RESERV", length = 7)
	public Date getDateReserv() {
		return this.dateReserv;
	}

	public void setDateReserv(Date dateReserv) {
		this.dateReserv = dateReserv;
	}

	@Column(name = "L_RESR", length = 260)
	public String getLResr() {
		return this.LResr;
	}

	public void setLResr(String LResr) {
		this.LResr = LResr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "AIR_PORT_DEPART", length = 260)
	public String getAirPortDepart() {
		return airPortDepart;
	}

	public void setAirPortDepart(String airPortDepart) {
		this.airPortDepart = airPortDepart;
	}

	@Column(name = "AIR_PORT_ARRIVE", length = 260)
	public String getAirPortArrive() {
		return airPortArrive;
	}

	public void setAirPortArrive(String airPortArrive) {
		this.airPortArrive = airPortArrive;
	}

	@Column(name = "HOTEL", length = 260)
	public String getHotel() {
		return hotel;
	}

	public void setHotel(String hotel) {
		this.hotel = hotel;
	}

	@Column(name = "VILLE_HOTEL", length = 260)
	public String getVilleHotel() {
		return villeHotel;
	}

	public void setVilleHotel(String villeHotel) {
		this.villeHotel = villeHotel;
	}

	@Column(name = "PAYS", length = 260)
	public String getPays() {
		return pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	@Column(name = "TYPE_CHAMBRE", length = 260)
	public String getTypeChambre() {
		return typeChambre;
	}

	public void setTypeChambre(String typeChambre) {
		this.typeChambre = typeChambre;
	}

	@Column(name = "CATEGORIE", length = 260)
	public String getCategorie() {
		return categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

}
