package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReservationId generated by hbm2java
 */
@Embeddable
public class ReservationId implements java.io.Serializable {

	private BigDecimal idRefTiers;
	private BigDecimal idReserv;

	public ReservationId() {
	}

	public ReservationId(BigDecimal idRefTiers, BigDecimal idReserv) {
		this.idRefTiers = idRefTiers;
		this.idReserv = idReserv;
	}

	@Column(name = "ID_REF_TIERS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdRefTiers() {
		return this.idRefTiers;
	}

	public void setIdRefTiers(BigDecimal idRefTiers) {
		this.idRefTiers = idRefTiers;
	}

	@Column(name = "ID_RESERV", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdReserv() {
		return this.idReserv;
	}

	public void setIdReserv(BigDecimal idReserv) {
		this.idReserv = idReserv;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservationId))
			return false;
		ReservationId castOther = (ReservationId) other;

		return ((this.getIdRefTiers() == castOther.getIdRefTiers()) || (this.getIdRefTiers() != null
				&& castOther.getIdRefTiers() != null && this.getIdRefTiers().equals(castOther.getIdRefTiers())))
				&& ((this.getIdReserv() == castOther.getIdReserv()) || (this.getIdReserv() != null
						&& castOther.getIdReserv() != null && this.getIdReserv().equals(castOther.getIdReserv())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdRefTiers() == null ? 0 : this.getIdRefTiers().hashCode());
		result = 37 * result + (getIdReserv() == null ? 0 : this.getIdReserv().hashCode());
		return result;
	}

}
