package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "ROLE")
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idRole;
	private String LRole;
	private String abrvRole;
	private Set<RefUsers> refUserses = new HashSet<RefUsers>(0);
	private Set<RoleFonction> roleFonctions = new HashSet<RoleFonction>(0);

	public Role() {
	}

	public Role(BigDecimal idRole, String abrvRole) {
		this.idRole = idRole;
		this.abrvRole = abrvRole;
	}

	public Role(BigDecimal idRole, String LRole, String abrvRole, Set<RefUsers> refUserses,
			Set<RoleFonction> roleFonctions) {
		this.idRole = idRole;
		this.LRole = LRole;
		this.abrvRole = abrvRole;
		this.refUserses = refUserses;
		this.roleFonctions = roleFonctions;
	}

	@Id

	@Column(name = "ID_ROLE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdRole() {
		return this.idRole;
	}

	public void setIdRole(BigDecimal idRole) {
		this.idRole = idRole;
	}

	@Column(name = "L_ROLE", length = 100)
	public String getLRole() {
		return this.LRole;
	}

	public void setLRole(String LRole) {
		this.LRole = LRole;
	}

	@Column(name = "ABRV_ROLE", nullable = false, length = 20)
	public String getAbrvRole() {
		return this.abrvRole;
	}

	public void setAbrvRole(String abrvRole) {
		this.abrvRole = abrvRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<RefUsers> getRefUserses() {
		return this.refUserses;
	}

	public void setRefUserses(Set<RefUsers> refUserses) {
		this.refUserses = refUserses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<RoleFonction> getRoleFonctions() {
		return this.roleFonctions;
	}

	public void setRoleFonctions(Set<RoleFonction> roleFonctions) {
		this.roleFonctions = roleFonctions;
	}

}
