package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleFonction generated by hbm2java
 */
@Entity
@Table(name = "ROLE_FONCTION")
public class RoleFonction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private RoleFonctionId id;
	private RefFonction refFonction;
	private Role role;
	private Character actifFonct;

	public RoleFonction() {
	}

	public RoleFonction(RoleFonctionId id, RefFonction refFonction, Role role) {
		this.id = id;
		this.refFonction = refFonction;
		this.role = role;
	}

	public RoleFonction(RoleFonctionId id, RefFonction refFonction, Role role, Character actifFonct) {
		this.id = id;
		this.refFonction = refFonction;
		this.role = role;
		this.actifFonct = actifFonct;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idFonction", column = @Column(name = "ID_FONCTION", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idRole", column = @Column(name = "ID_ROLE", nullable = false, precision = 22, scale = 0)) })
	public RoleFonctionId getId() {
		return this.id;
	}

	public void setId(RoleFonctionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FONCTION",  insertable = false, updatable = false)
	public RefFonction getRefFonction() {
		return this.refFonction;
	}

	public void setRefFonction(RefFonction refFonction) {
		this.refFonction = refFonction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ROLE",  insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "ACTIF_FONCT", length = 1)
	public Character getActifFonct() {
		return this.actifFonct;
	}

	public void setActifFonct(Character actifFonct) {
		this.actifFonct = actifFonct;
	}

}
