package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleFonctionId generated by hbm2java
 */
@Embeddable
public class RoleFonctionId implements java.io.Serializable {

	private BigDecimal idFonction;
	private BigDecimal idRole;

	public RoleFonctionId() {
	}

	public RoleFonctionId(BigDecimal idFonction, BigDecimal idRole) {
		this.idFonction = idFonction;
		this.idRole = idRole;
	}

	@Column(name = "ID_FONCTION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdFonction() {
		return this.idFonction;
	}

	public void setIdFonction(BigDecimal idFonction) {
		this.idFonction = idFonction;
	}

	@Column(name = "ID_ROLE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdRole() {
		return this.idRole;
	}

	public void setIdRole(BigDecimal idRole) {
		this.idRole = idRole;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleFonctionId))
			return false;
		RoleFonctionId castOther = (RoleFonctionId) other;

		return ((this.getIdFonction() == castOther.getIdFonction()) || (this.getIdFonction() != null
				&& castOther.getIdFonction() != null && this.getIdFonction().equals(castOther.getIdFonction())))
				&& ((this.getIdRole() == castOther.getIdRole()) || (this.getIdRole() != null
						&& castOther.getIdRole() != null && this.getIdRole().equals(castOther.getIdRole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdFonction() == null ? 0 : this.getIdFonction().hashCode());
		result = 37 * result + (getIdRole() == null ? 0 : this.getIdRole().hashCode());
		return result;
	}

}
