package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SupplementId generated by hbm2java
 */
@Embeddable
public class SupplementId implements java.io.Serializable {

	private BigDecimal idHotel;
	private BigDecimal idSupp;

	public SupplementId() {
	}

	public SupplementId(BigDecimal idHotel, BigDecimal idSupp) {
		this.idHotel = idHotel;
		this.idSupp = idSupp;
	}

	@Column(name = "ID_HOTEL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdHotel() {
		return this.idHotel;
	}

	public void setIdHotel(BigDecimal idHotel) {
		this.idHotel = idHotel;
	}

	@Column(name = "ID_SUPP", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSupp() {
		return this.idSupp;
	}

	public void setIdSupp(BigDecimal idSupp) {
		this.idSupp = idSupp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SupplementId))
			return false;
		SupplementId castOther = (SupplementId) other;

		return ((this.getIdHotel() == castOther.getIdHotel()) || (this.getIdHotel() != null
				&& castOther.getIdHotel() != null && this.getIdHotel().equals(castOther.getIdHotel())))
				&& ((this.getIdSupp() == castOther.getIdSupp()) || (this.getIdSupp() != null
						&& castOther.getIdSupp() != null && this.getIdSupp().equals(castOther.getIdSupp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdHotel() == null ? 0 : this.getIdHotel().hashCode());
		result = 37 * result + (getIdSupp() == null ? 0 : this.getIdSupp().hashCode());
		return result;
	}

}
