package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TypeChambre generated by hbm2java
 */
@Entity
@Table(name = "TYPE_CHAMBRE")
public class TypeChambre implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TypeChambreId id;
	private Hotel hotel;
	private String LTypeChm;
	private String abrvChambre;
	private String type;

	public TypeChambre() {
	}

	public TypeChambre(TypeChambreId id, Hotel hotel, String abrvChambre) {
		this.id = id;
		this.hotel = hotel;
		this.abrvChambre = abrvChambre;
	}

	public TypeChambre(TypeChambreId id, Hotel hotel, String LTypeChm, String abrvChambre, Set<Promotion> promotions,
			Set<MvmentPrix> mvmentPrixes) {
		this.id = id;
		this.hotel = hotel;
		this.LTypeChm = LTypeChm;
		this.abrvChambre = abrvChambre;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idHotel", column = @Column(name = "ID_HOTEL", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idChm", column = @Column(name = "ID_CHM", nullable = false, precision = 22, scale = 0)) })
	public TypeChambreId getId() {
		return this.id;
	}

	public void setId(TypeChambreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HOTEL", insertable = false, updatable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "L_TYPE_CHM", length = 200)
	public String getLTypeChm() {
		return this.LTypeChm;
	}

	public void setLTypeChm(String LTypeChm) {
		this.LTypeChm = LTypeChm;
	}

	@Column(name = "ABRV_CHAMBRE", nullable = false, length = 20)
	public String getAbrvChambre() {
		return this.abrvChambre;
	}

	public void setAbrvChambre(String abrvChambre) {
		this.abrvChambre = abrvChambre;
	}

	@Column(name = "TYPE", length = 20)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
