package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TypeChambreId generated by hbm2java
 */
@Embeddable
public class TypeChambreId implements java.io.Serializable {

	private BigDecimal idHotel;
	private BigDecimal idChm;

	public TypeChambreId() {
	}

	public TypeChambreId(BigDecimal idHotel, BigDecimal idChm) {
		this.idHotel = idHotel;
		this.idChm = idChm;
	}

	@Column(name = "ID_HOTEL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdHotel() {
		return this.idHotel;
	}

	public void setIdHotel(BigDecimal idHotel) {
		this.idHotel = idHotel;
	}

	@Column(name = "ID_CHM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdChm() {
		return this.idChm;
	}

	public void setIdChm(BigDecimal idChm) {
		this.idChm = idChm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TypeChambreId))
			return false;
		TypeChambreId castOther = (TypeChambreId) other;

		return ((this.getIdHotel() == castOther.getIdHotel()) || (this.getIdHotel() != null
				&& castOther.getIdHotel() != null && this.getIdHotel().equals(castOther.getIdHotel())))
				&& ((this.getIdChm() == castOther.getIdChm()) || (this.getIdChm() != null
						&& castOther.getIdChm() != null && this.getIdChm().equals(castOther.getIdChm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdHotel() == null ? 0 : this.getIdHotel().hashCode());
		result = 37 * result + (getIdChm() == null ? 0 : this.getIdChm().hashCode());
		return result;
	}

}
