package com.worldsoft.domain;
// Generated 31 mars 2016 10:57:06 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeVol generated by hbm2java
 */
@Entity
@Table(name = "TYPE_VOL")
public class TypeVol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idTypeVol;
	private String categVol;
	private String LVol;
	private String abrvVol;
	private Set<MvmentPrix> mvmentPrixes = new HashSet<MvmentPrix>(0);

	public TypeVol() {
	}

	public TypeVol(BigDecimal idTypeVol, String abrvVol) {
		this.idTypeVol = idTypeVol;
		this.abrvVol = abrvVol;
	}

	public TypeVol(BigDecimal idTypeVol, String categVol, String LVol, String abrvVol,
			Set<MvmentPrix> mvmentPrixes) {
		this.idTypeVol = idTypeVol;
		this.categVol = categVol;
		this.LVol = LVol;
		this.abrvVol = abrvVol;
		this.mvmentPrixes = mvmentPrixes;
	}

	@Id

	@Column(name = "ID_TYPE_VOL", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTypeVol() {
		return this.idTypeVol;
	}

	public void setIdTypeVol(BigDecimal idTypeVol) {
		this.idTypeVol = idTypeVol;
	}

	@Column(name = "CATEG_VOL", length = 20)
	public String getCategVol() {
		return this.categVol;
	}

	public void setCategVol(String categVol) {
		this.categVol = categVol;
	}

	@Column(name = "L_VOL", length = 100)
	public String getLVol() {
		return this.LVol;
	}

	public void setLVol(String LVol) {
		this.LVol = LVol;
	}

	@Column(name = "ABRV_VOL", nullable = false, precision = 22, scale = 0)
	public String getAbrvVol() {
		return this.abrvVol;
	}

	public void setAbrvVol(String abrvVol) {
		this.abrvVol = abrvVol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeVol")
	public Set<MvmentPrix> getMvmentPrixes() {
		return this.mvmentPrixes;
	}

	public void setMvmentPrixes(Set<MvmentPrix> mvmentPrixes) {
		this.mvmentPrixes = mvmentPrixes;
	}

}
